<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require ('innerlib.php');
use Zend\Http\PhpEnvironment\Request;
chdir(dirname(__DIR__));
require_once(realpath(__DIR__ . DIRECTORY_SEPARATOR . '..').'/vendor/autoload.php');
require_once('FirePHPCore/fb.php');

if (isset($_POST['username']) && isset($_POST['password'])) {

    $UserName=$_POST['username'];
    $Password=$_POST['password'];
    if ($UserName && $Password) {
        try {
            $db = DBConnect();
            $sql = "call SignIn(:UserName);";
            $stmt = $db->prepare($sql);
            $stmt->bindParam(":UserName", $UserName,PDO::PARAM_STR,255);
            $stmt->execute();
            $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
            if (isset($result[0])) {

                /*
                 * Password was generated by password_hash(), so we need to use
                 * password_verify() to check it.
                 */
                if (password_verify($Password, $result[0]['Password'])) {
                    OutResult('OuterMethodList', $UserName, '');
                } else {
                    header('HTTP/1.0 401 Unauthorized');
                }
            } else {
                header('HTTP/1.0 404 Not Found');
            }
        } catch (Exception $e) {
            header('HTTP/1.0 500 Internal Server Errorr');
        }
    } else {
        header('HTTP/1.0 400 Bad Request');
    }
}else if(isset($_POST['Authorization'])){
    $jwt = $_POST['Authorization'];
    $UserName = ValidateToken($jwt);
    if($UserName != null){
    	$Method = $_POST['MethodName'];
        unset($_POST['MethodName']);
        unset($_POST['Authorization']);
        OutResult($Method, $UserName,$_POST);
     }else {
     	header('HTTP/1.0 401 Unauthorized');
     }
}else {
    header('HTTP/1.0 405 Method Not Allowed');
}